CREATE DATABASE IF NOT EXISTS {{ CINDER_DB_NAME }};

CREATE USER IF NOT EXISTS '{{ CINDER_DB_USER }}'@'%' IDENTIFIED BY '{{ CINDER_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON {{ CINDER_DB_NAME }}.* TO '{{ CINDER_DB_USER }}'@'%';
