CREATE DATABASE IF NOT EXISTS {{ NEUTRON_DB_NAME }};

CREATE USER IF NOT EXISTS '{{ NEUTRON_DB_USER }}'@'%' IDENTIFIED BY '{{ NEUTRON_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON {{ NEUTRON_DB_NAME }}.* TO '{{ NEUTRON_DB_USER }}'@'%';

