CREATE DATABASE IF NOT EXISTS {{ PLACEMENT_DB_NAME }};

CREATE USER IF NOT EXISTS '{{ PLACEMENT_DB_USER }}'@'%' IDENTIFIED BY '{{ PLACEMENT_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON {{ PLACEMENT_DB_NAME }}.* TO '{{ PLACEMENT_DB_USER }}'@'%';


