CREATE DATABASE IF NOT EXISTS placement;

CREATE USER IF NOT EXISTS 'placement'@'localhost' IDENTIFIED BY 'anq9SXHR';
CREATE USER IF NOT EXISTS 'placement'@'%' IDENTIFIED BY 'anq9SXHR';

GRANT ALL PRIVILEGES ON placement.* TO 'placement'@'%';


