CREATE DATABASE IF NOT EXISTS {{ NOVA_API_DB_NAME }};
CREATE DATABASE IF NOT EXISTS {{ NOVA_DB_NAME }};
CREATE DATABASE IF NOT EXISTS {{ NOVA_CELL0_DB_NAME }};

CREATE USER IF NOT EXISTS '{{ NOVA_DB_USER }}'@'%' IDENTIFIED BY '{{ NOVA_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON {{ NOVA_API_DB_NAME }}.* TO '{{ NOVA_DB_USER }}'@'%';
GRANT ALL PRIVILEGES ON {{ NOVA_DB_NAME }}.* TO '{{ NOVA_DB_USER }}'@'%';
GRANT ALL PRIVILEGES ON {{ NOVA_CELL0_DB_NAME }}.* TO '{{ NOVA_DB_USER }}'@'%';