CREATE DATABASE IF NOT EXISTS keystone;

CREATE USER IF NOT EXISTS '{{ KEYSTONE_DB_USER }}'@'%' IDENTIFIED BY '{{ KEYSTONE_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON keystone.* TO '{{ KEYSTONE_DB_USER }}'@'%';


