CREATE DATABASE IF NOT EXISTS {{ KEYSTONE_DB_NAME }};

CREATE USER IF NOT EXISTS '{{ KEYSTONE_DB_USER }}'@'%' IDENTIFIED BY '{{ KEYSTONE_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON {{ KEYSTONE_DB_NAME }}.* TO '{{ KEYSTONE_DB_USER }}'@'%';


