CREATE DATABASE IF NOT EXISTS {{ GLANCE_DB_NAME }};

CREATE USER IF NOT EXISTS '{{ GLANCE_DB_USER }}'@'%' IDENTIFIED BY '{{ GLANCE_DB_PASSWORD }}';

GRANT ALL PRIVILEGES ON {{ GLANCE_DB_NAME }}.* TO '{{ GLANCE_DB_USER }}'@'%';
